# Netlify Configuration for SmartBite Frontend
# Automated deployment configuration for app.moduly.ai

[build]
  command = "echo 'Builds disabled - using GitHub Actions only'"
  publish = "dist"
  ignore = "true"  # Disable Netlify auto-builds - GitHub Actions handles deployment

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# All environment configuration now managed via GitHub Actions and GitHub Secrets
# No hard-coded values - secure deployment only through CI/CD pipeline

# SPA routing - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Cache static assets for 1 year
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache HTML files for 10 minutes
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=600"

# Environment-specific builds (optional advanced configuration)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true